const TARGET_ORIGIN = "https://pwxmarco.pages.dev";
const PROXY_PREFIX = "/api/proxy/";

// Headers we never forward to the origin
const STRIP_REQUEST_HEADERS = new Set([
  "host",
  "connection",
  "content-length",
  "accept-encoding",
  "cf-connecting-ip",
  "cf-ray",
  "cf-visitor",
  "cf-ipcountry",
  "x-forwarded-for",
  "x-forwarded-proto",
  "x-real-ip",
]);

// Headers we never send back to the browser
const STRIP_RESPONSE_HEADERS = new Set([
  "content-encoding",
  "content-length",
  "transfer-encoding",
  "connection",
  // frame-busting / isolation headers must go so the proxy page can be iframed
  "x-frame-options",
  "content-security-policy",
  "content-security-policy-report-only",
  "cross-origin-opener-policy",
  "cross-origin-embedder-policy",
  "cross-origin-resource-policy",
]);

/**
 * Frontend-only content rewrites applied to proxied HTML.
 * Nothing on the origin backend is modified — we only transform
 * the markup before it is rendered in the browser.
 */
function rewriteHtml(html: string): string {
  let out = html;

  // 1. Frontend replacement: swap the Telegram link.
  out = out
    .replaceAll("t.me/official_marco_22", "t.me/PWNexuss")
    .replaceAll("telegram.me/official_marco_22", "telegram.me/PWNexuss")
    .replaceAll("@official_marco_22", "@PWNexuss");

  // The player owns its Back control. Only a direct click on its Telegram
  // anchor may navigate the top-level page; browser/device Back is untouched.
  const playerBackClickHandler = `<script>(function(){document.addEventListener("click",function(event){var node=event.target instanceof Element?event.target.closest("a[href]"):null;if(!node)return;var href=node.getAttribute("href")||"";if(!/^(?:https?:\\/\\/)?(?:t|telegram)\\.me\\/PWNexuss(?:[/?#]|$)/i.test(href))return;event.preventDefault();event.stopImmediatePropagation();window.top.location.replace("https://t.me/PWNexuss");},true);})();</script>`;
  if (/<head[^>]*>/i.test(out)) {
    out = out.replace(/<head([^>]*)>/i, `<head$1>${playerBackClickHandler}`);
  } else {
    out = playerBackClickHandler + out;
  }

  // 2. Keep media requests generated by the player's frontend shim inside
  // this proxy. The full signed media path and query string remain unchanged.
  out = out.replaceAll('"/__media_proxy__/', `"${PROXY_PREFIX}__media_proxy__/`);

  // 3. Point absolute origin URLs back through the proxy.
  out = out.replaceAll(`${TARGET_ORIGIN}/`, PROXY_PREFIX);

  // 4. Root-relative attributes (href="/x", src="/x", action="/x") -> proxied path.
  out = out.replace(
    /((?:href|src|action)\s*=\s*)(["'])\/(?!api\/proxy\/|\/)([^"']*)\2/gi,
    (_m, attr: string, quote: string, path: string) =>
      `${attr}${quote}${PROXY_PREFIX}${path}${quote}`,
  );

  // 5. Relative URLs: inject a <base> so the browser resolves them through the
  // proxy, plus early connection hints so the player's assets and media
  // requests do not pay DNS/TLS cost after the document arrives.
  if (/<head[^>]*>/i.test(out)) {
    out = out.replace(
      /<head([^>]*)>/i,
      `<head$1><base href="${PROXY_PREFIX}"><link rel="preconnect" href="${TARGET_ORIGIN}" crossorigin><link rel="dns-prefetch" href="${TARGET_ORIGIN}">`,
    );
  }

  return out;
}

function rewriteCss(css: string): string {
  return css.replace(
    /url\(\s*(["']?)\/(?!api\/proxy\/)([^)"']+)\1\s*\)/gi,
    (_m, quote: string, path: string) => `url(${quote}${PROXY_PREFIX}${path}${quote})`,
  );
}

/**
 * The upstream player page is slow to answer (server-side work on the origin).
 * Two guards keep us from ever paying that cost more than once:
 *  - in-flight coalescing: concurrent requests for the same URL share one fetch
 *  - a very short-lived document cache for immediate repeats (reload, hydration)
 * Signed media/asset requests are never cached — only the player document.
 */
const inFlight = new Map<string, Promise<{ body: string; init: ResponseInit }>>();
const docCache = new Map<string, { body: string; init: ResponseInit; expires: number }>();
const DOC_CACHE_MS = 15_000;

function buildRequestHeaders(request: Request): Headers {
  const headers = new Headers();
  request.headers.forEach((value, key) => {
    if (!STRIP_REQUEST_HEADERS.has(key.toLowerCase())) headers.set(key, value);
  });
  // Present a normal browser identity to the origin.
  // The origin rejects bot-like user agents; upgrade anything that isn't a real browser.
  const BROWSER_UA =
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36";
  const incomingUa = request.headers.get("user-agent") ?? "";
  headers.set(
    "user-agent",
    /mozilla|chrome|safari|firefox|edg|opera/i.test(incomingUa) ? incomingUa : BROWSER_UA,
  );
  headers.set("referer", `${TARGET_ORIGIN}/`);
  headers.set("origin", TARGET_ORIGIN);
  // Compressed transfer is decoded transparently by fetch and is measurably
  // faster than forcing identity on the (large) player document.
  headers.set("accept-encoding", "gzip, br");
  return headers;
}

function buildResponseHeaders(upstream: Response, targetUrl: string): Headers {
  const responseHeaders = new Headers();
  upstream.headers.forEach((value, key) => {
    if (!STRIP_RESPONSE_HEADERS.has(key.toLowerCase())) responseHeaders.set(key, value);
  });

  // Rewrite redirects so the browser stays on the proxy.
  const location = responseHeaders.get("location");
  if (location) {
    const resolved = new URL(location, targetUrl);
    if (resolved.origin === TARGET_ORIGIN) {
      responseHeaders.set(
        "location",
        `${PROXY_PREFIX}${resolved.pathname.replace(/^\//, "")}${resolved.search}${resolved.hash}`,
      );
    } else {
      responseHeaders.set("location", resolved.toString());
    }
  }

  // Rewrite cookie domains so they bind to this host.
  const setCookies: string[] = [];
  responseHeaders.forEach((value, key) => {
    if (key.toLowerCase() === "set-cookie") setCookies.push(value);
  });
  if (setCookies.length > 0) {
    responseHeaders.delete("set-cookie");
    for (const cookie of setCookies) {
      responseHeaders.append("set-cookie", cookie.replace(/;\s*Domain=[^;]*/gi, ""));
    }
  }

  return responseHeaders;
}

function headersToObject(headers: Headers): [string, string][] {
  const entries: [string, string][] = [];
  headers.forEach((value, key) => entries.push([key, value]));
  return entries;
}

export async function handleProxy(request: Request, splat: string): Promise<Response> {
  const incoming = new URL(request.url);
  const targetUrl = `${TARGET_ORIGIN}/${splat}${incoming.search}`;
  const isDocumentRequest =
    request.method === "GET" && /(^|\/)[^/]*\.php$/i.test(splat.split("?")[0]);
  const cacheKey = targetUrl;

  if (isDocumentRequest) {
    const cached = docCache.get(cacheKey);
    if (cached && cached.expires > Date.now()) {
      return new Response(cached.body, cached.init);
    }
    const pending = inFlight.get(cacheKey);
    if (pending) {
      const { body, init } = await pending;
      return new Response(body, init);
    }
  }

  const fetchUpstream = async () => {
    const upstream = await fetch(targetUrl, {
      method: request.method,
      headers: buildRequestHeaders(request),
      body: null,
      redirect: "manual",
    });
    const responseHeaders = buildResponseHeaders(upstream, targetUrl);
    const html = await upstream.text();
    responseHeaders.set("content-type", "text/html; charset=utf-8");
    return {
      body: rewriteHtml(html),
      init: {
        status: upstream.status,
        headers: headersToObject(responseHeaders),
      } satisfies ResponseInit,
      cacheable: upstream.status === 200,
    };
  };

  if (isDocumentRequest) {
    const task = fetchUpstream().then(({ body, init, cacheable }) => {
      if (cacheable) docCache.set(cacheKey, { body, init, expires: Date.now() + DOC_CACHE_MS });
      return { body, init };
    });
    inFlight.set(cacheKey, task);
    try {
      const { body, init } = await task;
      return new Response(body, init);
    } finally {
      inFlight.delete(cacheKey);
    }
  }

  const hasBody = request.method !== "GET" && request.method !== "HEAD";
  const upstream = await fetch(targetUrl, {
    method: request.method,
    headers: buildRequestHeaders(request),
    body: hasBody ? await request.arrayBuffer() : null,
    redirect: "manual",
  });

  const responseHeaders = buildResponseHeaders(upstream, targetUrl);
  const contentType = upstream.headers.get("content-type") ?? "";

  if (contentType.includes("text/html")) {
    const html = await upstream.text();
    responseHeaders.set("content-type", "text/html; charset=utf-8");
    return new Response(rewriteHtml(html), { status: upstream.status, headers: responseHeaders });
  }

  if (contentType.includes("text/css")) {
    const css = await upstream.text();
    responseHeaders.set("content-type", contentType);
    return new Response(rewriteCss(css), { status: upstream.status, headers: responseHeaders });
  }

  return new Response(upstream.body, { status: upstream.status, headers: responseHeaders });
}
