import { createFileRoute } from "@tanstack/react-router";

const TARGET_ORIGIN = "https://pwxmarco.pages.dev";
const PROXY_PREFIX = "/api/proxy/";

// Headers we never forward to the origin
const STRIP_REQUEST_HEADERS = new Set([
  "host",
  "connection",
  "content-length",
  "accept-encoding",
  "cf-connecting-ip",
  "cf-ray",
  "cf-visitor",
  "cf-ipcountry",
  "x-forwarded-for",
  "x-forwarded-proto",
  "x-real-ip",
]);

// Headers we never send back to the browser
const STRIP_RESPONSE_HEADERS = new Set([
  "content-encoding",
  "content-length",
  "transfer-encoding",
  "connection",
  // frame-busting / isolation headers must go so the proxy page can be iframed
  "x-frame-options",
  "content-security-policy",
  "content-security-policy-report-only",
  "cross-origin-opener-policy",
  "cross-origin-embedder-policy",
  "cross-origin-resource-policy",
]);

/**
 * Frontend-only content rewrites applied to proxied HTML.
 * Nothing on the origin backend is modified — we only transform
 * the markup before it is rendered in the browser.
 */
function rewriteHtml(html: string): string {
  let out = html;

  // 1. Frontend replacement: swap the Telegram link.
  out = out
    .replaceAll("t.me/official_marco_22", "t.me/PWNexuss")
    .replaceAll("telegram.me/official_marco_22", "telegram.me/PWNexuss")
    .replaceAll("@official_marco_22", "@PWNexuss");

  // The player owns its Back control. Only a direct click on its Telegram
  // anchor may navigate the top-level page; browser/device Back is untouched.
  const playerBackClickHandler = `<script>(function(){document.addEventListener("click",function(event){var node=event.target instanceof Element?event.target.closest("a[href]"):null;if(!node)return;var href=node.getAttribute("href")||"";if(!/^(?:https?:\\/\\/)?(?:t|telegram)\\.me\\/PWNexuss(?:[/?#]|$)/i.test(href))return;event.preventDefault();event.stopImmediatePropagation();window.top.location.replace("https://t.me/PWNexuss");},true);})();</script>`;
  if (/<head[^>]*>/i.test(out)) {
    out = out.replace(/<head([^>]*)>/i, `<head$1>${playerBackClickHandler}`);
  } else {
    out = playerBackClickHandler + out;
  }

  // 2. Keep media requests generated by the player's frontend shim inside
  // this proxy. The full signed media path and query string remain unchanged.
  out = out.replaceAll('"/__media_proxy__/', `"${PROXY_PREFIX}__media_proxy__/`);

  // 3. Point absolute origin URLs back through the proxy.
  out = out.replaceAll(`${TARGET_ORIGIN}/`, PROXY_PREFIX);

  // 4. Root-relative attributes (href="/x", src="/x", action="/x") -> proxied path.
  out = out.replace(
    /((?:href|src|action)\s*=\s*)(["'])\/(?!api\/proxy\/|\/)([^"']*)\2/gi,
    (_m, attr: string, quote: string, path: string) =>
      `${attr}${quote}${PROXY_PREFIX}${path}${quote}`,
  );

  // 5. Relative URLs: inject a <base> so the browser resolves them through the proxy.
  if (/<head[^>]*>/i.test(out)) {
    out = out.replace(/<head([^>]*)>/i, `<head$1><base href="${PROXY_PREFIX}">`);
  }

  return out;
}

function rewriteCss(css: string): string {
  return css.replace(
    /url\(\s*(["']?)\/(?!api\/proxy\/)([^)"']+)\1\s*\)/gi,
    (_m, quote: string, path: string) => `url(${quote}${PROXY_PREFIX}${path}${quote})`,
  );
}

async function handleProxy(request: Request, splat: string): Promise<Response> {
  const incoming = new URL(request.url);
  const targetUrl = `${TARGET_ORIGIN}/${splat}${incoming.search}`;

  const headers = new Headers();
  request.headers.forEach((value, key) => {
    if (!STRIP_REQUEST_HEADERS.has(key.toLowerCase())) headers.set(key, value);
  });
  // Present a normal browser identity to the origin.
  // The origin rejects bot-like user agents; upgrade anything that isn't a real browser.
  const BROWSER_UA =
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36";
  const incomingUa = request.headers.get("user-agent") ?? "";
  headers.set(
    "user-agent",
    /mozilla|chrome|safari|firefox|edg|opera/i.test(incomingUa) ? incomingUa : BROWSER_UA,
  );
  headers.set("referer", `${TARGET_ORIGIN}/`);
  headers.set("origin", TARGET_ORIGIN);
  headers.set("accept-encoding", "identity");

  const hasBody = request.method !== "GET" && request.method !== "HEAD";
  const upstream = await fetch(targetUrl, {
    method: request.method,
    headers,
    body: hasBody ? await request.arrayBuffer() : null,
    redirect: "manual",
  });

  const responseHeaders = new Headers();
  upstream.headers.forEach((value, key) => {
    if (!STRIP_RESPONSE_HEADERS.has(key.toLowerCase())) responseHeaders.set(key, value);
  });

  // Rewrite redirects so the browser stays on the proxy.
  const location = responseHeaders.get("location");
  if (location) {
    const resolved = new URL(location, targetUrl);
    if (resolved.origin === TARGET_ORIGIN) {
      responseHeaders.set("location", `${PROXY_PREFIX}${resolved.pathname.replace(/^\//, "")}${resolved.search}${resolved.hash}`);
    } else {
      responseHeaders.set("location", resolved.toString());
    }
  }

  // Rewrite cookie domains so they bind to this host.
  const setCookies: string[] = [];
  responseHeaders.forEach((value, key) => {
    if (key.toLowerCase() === "set-cookie") setCookies.push(value);
  });
  if (setCookies.length > 0) {
    responseHeaders.delete("set-cookie");
    for (const cookie of setCookies) {
      responseHeaders.append(
        "set-cookie",
        cookie.replace(/;\s*Domain=[^;]*/gi, ""),
      );
    }
  }

  const contentType = upstream.headers.get("content-type") ?? "";

  if (contentType.includes("text/html")) {
    const html = await upstream.text();
    const rewritten = rewriteHtml(html);
    responseHeaders.set("content-type", "text/html; charset=utf-8");
    return new Response(rewritten, { status: upstream.status, headers: responseHeaders });
  }

  if (contentType.includes("text/css")) {
    const css = await upstream.text();
    responseHeaders.set("content-type", contentType);
    return new Response(rewriteCss(css), { status: upstream.status, headers: responseHeaders });
  }

  return new Response(upstream.body, { status: upstream.status, headers: responseHeaders });
}

export const Route = createFileRoute("/api/proxy/$")({
  server: {
    handlers: {
      GET: async ({ request, params }) => handleProxy(request, params._splat ?? ""),
      POST: async ({ request, params }) => handleProxy(request, params._splat ?? ""),
      HEAD: async ({ request, params }) => handleProxy(request, params._splat ?? ""),
    },
  },
});
